--- #YAML:1.0
name:               Grid-Request
version:            0.4
abstract:           Easily formulate, submit, and monitor grid jobs.
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              0
    Config::IniFiles:  2.19
    Exception::Class:  1.23
    File::Path:        1.0403
    File::Temp:        0.12
    File::Which:       0
    FindBin:           0
    IO::Scalar:        2.104
    Log::Log4perl:     1.08
    Schedule::DRMAAc:  0
    Sys::Hostname:     1.1
    Test::MockObject:  0
    Test::More:        0.46
    XML::Writer:       0.4
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
